#! /usr/bin/python3

# Copyright © 2015-2020 Vladimir Olteanu <vl.olteanu@gmail.com>
# This program is free software. It comes without any warranty, to
# the extent permitted by applicable law. You can redistribute it
# and/or modify it under the terms of the Do What The Fuck You Want
# To Public License, Version 2, as published by Sam Hocevar. See
# the COPYING file for more details.

import os
import sys
import subprocess

CONFIG_PATH = '/etc/butterback/'
ROOT_PATH   = CONFIG_PATH + 'root'
TARGET_PATH = CONFIG_PATH + "targets/"
DATE_FMT    = "%Y-%m-%d-%T"

def exec(cmd):
	print(cmd)
	subprocess.run(cmd, check = True)

def get_oneline_output(cmd):
	raw_out = subprocess.check_output(cmd)
	raw_out = raw_out[:len(raw_out) - 1] #strip \n
	
	return raw_out.decode("utf-8")

def date():
	return get_oneline_output(['date', '+' + DATE_FMT])

class Host:
	def backup(self, source, dest):
		if (not self.is_dir(dest)):
			self.run(['mkdir', '-p', dest])
		
		current_path = dest + '/current'
		if (not self.is_dir(current_path)):
			self.run_root(['btrfs', 'subvolume', 'create', current_path])
			self.run_root(['chown', self.get_user(), current_path])
		
		exec(['rsync',  '-a',  '--delete',  '--progress', source, self.rsync_pref() + current_path])
	
		snap_path = dest + '/' + date()
		self.run_root(['btrfs', 'subvolume', 'snapshot', current_path, snap_path])
		
	def restore(self, source, dest):
		if (not self.is_dir(dest)):
			self.run(['mkdir', '-p', dest])
		exec(['rsync',  '-a', '--delete', '--progress', source, dest])
		
class LocalHost(Host):
	def run(self, cmd):
		exec(cmd)
	
	def run_root(self, cmd):
		exec(['sudo'] + cmd)
	
	def is_dir(self, path):
		return os.path.isdir(path)
	
	def get_user(self):
		return get_oneline_output(['whoami'])
	
	def rsync_pref(self):
		return ''

class RemoteHost(Host):
	def __init__(self, user, host):
		if (host == ''):
			raise Exception('Empty hostname');
		if (user == ''):
			user = get_oneline_output(['ssh', host, 'whoami'])
		self.user = user
		self.host = host
		
	def ssh_host(self):
		return self.user + '@' + self.host
	
	def run(self, cmd):
		exec(['ssh', self.ssh_host()] + cmd)
	
	def run_root(self, cmd):
		exec(['ssh', 'root@' + self.host] + cmd)
	
	def is_dir(self, path):
		try:
			self.run(['[ -d "{}" ]'.format(path)])
		except:
			return False
		return True
	
	def get_user(self):
		return self.user
		
	def rsync_pref(self):
		return self.ssh_host() + ':'

def separate_host(str):
	str_tokens = str.split(':')
	if (len(str_tokens) == 1):
		return [LocalHost(), str]
	elif (len(str_tokens) > 2):
		raise Exception('Bad root: ' + str)
	
	full_host = str_tokens[0]
	root = str_tokens[1]
	
	host_tokens = full_host.split('@')
	if (len(host_tokens) > 2):
		raise Exception('Bad root: ' + str)
	if (len(host_tokens) == 1):
		user = ''
		host = host_tokens[0]
	else:
		user = host_tokens[0]
		host = host_tokens[1]
	
	return [RemoteHost(user, host), root]

def parse_root_file(path):
	if (os.path.isdir(ROOT_PATH)):
		return [LocalHost(), ROOT_PATH]
	
	file = open(ROOT_PATH)
	lines = file.readlines()
	file.close()
	
	if (len(lines) == 0):
		raise Exception("Bad root file format")
	for i in range(1, len(lines)):
		if (not lines[i].isspace()):
			raise Exception("Bad root file format")
	
	first_line = lines[0]
	first_line = first_line[:len(first_line) - 1] #strip \n
	
	return separate_host(first_line)

def usage(rc = 1):
	print('Usage: butterback <command> <command args>')
	print('\t' + 'backup <source> <destination> ')
	print('\t' + 'restore <source> <destination>')
	print('\t' + 'auto')
	print('\t' + 'help')
	
	sys.exit(rc)
	
def main(argv):
	if (len(argv) == 0):
		usage()
	elif (len(argv) == 1):
		if (argv[0] == 'auto'):
			[host, root] = parse_root_file(ROOT_PATH)
			
			for i in os.listdir(TARGET_PATH):
				host.backup(TARGET_PATH + i, root + '/' + i)
		elif (argv[0] == 'help'):
			usage(0)
		else:
			usage()
	else:
		if (argv[0] == 'backup'):
			if (len(argv) != 3):
				usage()
			[host, dest] = separate_host(argv[2])
			host.backup(argv[1], dest)
		elif (argv[0] == 'restore'):
			if (len(argv) != 3):
				usage()
			[host, source] = separate_host(argv[1])
			host.restore(source, argv[2])
		else:
			usage()

if __name__ == "__main__":
	main(sys.argv[1:])
